name: CICD

on:
  workflow_dispatch: 

jobs:
  code:
    runs-on:  ubuntu-latest
    steps:
      - name: clone the code
        run: echo "clone the code"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "building using Docker"

  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Running test case
      run: echo "testing the app"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on server
        run: echo "Deploying the code to server"
        
      
